version: '3'
services:
  backend:
    build: ./
    command: bash -c "sleep 10 && node index.js"
    ports:
      - "5000:5000"
    depends_on:
      - database
  database:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - test-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1212
      MYSQL_DATABASE: Book
    container_name: mysql-db

volumes:
  test-vol: